<!DOCTYPE> 
<html>
<head>
<meta charset="utf-8"> 
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" /> 
<title></title> 


</head> 
<body> 
 <div class="cut-time">
        <?php if($pro['vipid'] && $pro['vip_info']['vip_endtime']-time()>0):?>
            <span style="float: left;">剩余：</span>
        <div class="lxftime2" endtime="<?=$pro['vip_info']['vip_endtime']-time();?>" style="float: left;"></div>
        <?php elseif($pro['tend_time']-time()>0):?>
            <span style="float: left;">剩余：</span>
            <div class="lxftime2" endtime="<?=$pro['tend_time']-time();?>"></div>
        <?php elseif($pro['status']==3):?>
            <span style="float: left;">专注母婴12年 正品保障</span>
        <?php endif;?>
</div>

<script language="javascript" type="text/javascript"> 
/*
time() php中得到的是秒，是从数据库中取得的。不会变。
自定义属性不加.
 */
var vnumb =0;
function ShowCountDown(){ 
    vnumb++;
    var times = $('.lxftime2').attr('endtime')-vnumb;
    var day = Math.floor( times/86400);
    var hour = Math.floor( times%86400/3600);
    var minute = Math.floor( times%86400%3600/60);
    var second = Math.floor( times%60);
    var cc = $('.lxftime2'); 
    cc.html(day+"天"+hour+"小时"+minute+"分"+second+"秒")
    console.log(cc);
} 
window.setInterval(function(){ShowCountDown();}, 1000); 
</script> 
</body> 
</html> 
